<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BLL\Journey.Services.Contracts\Journey.Services.Contracts.csproj" />
    <ProjectReference Include="..\..\BLL\Journey.Services\Journey.Services.csproj" />
    <ProjectReference Include="..\..\DAL\Journey.Storage.Contracts\Journey.Storage.Contracts.csproj" />
    <ProjectReference Include="..\..\DAL\Journey.Storage.EFStorage\Journey.Storage.EFStorage.csproj" />
    <ProjectReference Include="..\..\Journey.Models\Journey.Models.csproj" />
  </ItemGroup>

</Project>
